### PR TITLE
Add an option to provide a different rpcURL

### PR DESCRIPTION
**Pull request by leggechr**
- Updated the package.json so it builds on install
- Upgraded the ethers version
- added a `GetABIFetchers` option that allows the caller to pass in their own rpcURL for different networks.

### CODE REVIEW

**Review by nambrot — APPROVED** [review]

**Comment by leggechr** [comment]
Can you please merge? I don't have write access.

**Comment by nambrot** [comment]
I unfortunately, also don't have write access but I'll try to get someone to do it

**Comment by leggechr** [comment]
Thanks for the merge! @nambrot could you also publish the latest version to npm so I can get the changes? I think this needs to happen on your side?

**Comment by nambrot** [comment]
Published under 0.0.2

**Pull request merged**
